image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "" 
  DOCKER_DRIVER: overlay2
  DOCKER_PRIVILEGED_MODE: "true"

before_script:
  - apk add --no-cache docker-cli python3 py3-pip curl
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install pylint flask requests

stages:
  - lint
  - build
  - test
  - deploy

lint:
  stage: lint
  tags:
    - docker
  script:
    - source venv/bin/activate
    - pylint service1/app.py --fail-under=5  
  rules:
    - changes:
        - service1/app.py

build:
  stage: build
  tags:
    - docker
  script:
    - docker info
    - docker-compose build
  rules:
    - changes:
        - docker-compose.yaml
        - Dockerfile
        - service1/*
        - service2/*
  artifacts:
    paths:
      - build_logs/
    expire_in: 1 week

test:
  stage: test
  tags:
    - docker
  script:
    - docker-compose up -d
    - python -m unittest discover -s tests
    - docker-compose down
  dependencies:
    - build
  rules:
    - changes:
        - tests/*
        - service1/*
        - service2/*

deploy:
  tags:
    - docker
  stage: deploy
  script:
    - docker-compose up -d
