image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "" 
  DOCKER_DRIVER: overlay2
  DOCKER_PRIVILEGED_MODE: "true"

before_script:
  - apk add --no-cache docker-cli python3 py3-pip curl
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install pylint flask requests

stages:
  - lint
  - build
  - test

# Lint Stage
lint:
  stage: lint
  tags:
    - docker
  script:
    - source venv/bin/activate
    - pylint service1/app.py --fail-under=5

# Build Stage
build:
  stage: build
  tags:
    - docker
  script:
    - docker info
    - docker-compose build
  only:
    - main

# Test Stage
test:
  stage: test
  tags:
    - docker
  script:
    - docker-compose up -d
    - python -m unittest discover -s tests
    - docker-compose down
  only:
    - main
