version: '3.8'
services:
  service1:
    build: ./service1
    ports:
      - "8197:8197"
    depends_on:
      - service2
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8197/state || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3

  service2:
    build: ./service2
    ports:
      - "8199:8199"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8199/info || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
