upstream backend {
    server service1:8199;    
}

server {
    listen 80;
    include /etc/nginx/mime.types;
    location / {
        auth_basic             "Restricted Content";
        auth_basic_user_file   .htpasswd;
        proxy_pass http://backend/;
    }
}